# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 672038c5435af107f36e29445106439f9b46414bb77b8c2317a9902162c3efe71a43119c401046ba6f21edc52f9da694669fb031eb37cf6430f5080c0744f92d

test:
  secret_key_base: 85b22d689b233b67a37f5c04bd7dd2ded2b6220c9e9a383406e637e46833b6e9268c9c7e5532f9dbb85b3fdcbafea163b6696b713df15653aafe3791efa7fe21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
